apiVersion: v1
kind: Secret
metadata:
  name: coalita-db-superuser
  namespace: coalita
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: CHANGE_ME_strong_password_here
---
apiVersion: v1
kind: Secret
metadata:
  name: coalita-db-app
  namespace: coalita
type: kubernetes.io/basic-auth
stringData:
  username: coalita
  password: CHANGE_ME_strong_password_here
